# Версия docker-compose
version: '3'
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - ./logs:/var/log/nginx
    restart: always
    depends_on:
      - php
      - postgres
    environment:
      TZ: ${TZ}  
    networks:
      - backend    
  php:
    container_name: php
    build: 
      context: ./www/app
      args: 
        PHP_VERSION: ${PHP_VERSION}
        TZ: ${TZ}
    restart: always
    env_file:
      - ".env" 
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./www/app:/var/www/app
    depends_on:
      - postgres
    networks:
      - backend          
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    volumes:
      - ./etc/postgres/data:/var/lib/postgresql/data
      - ./etc/postgres/dump:/var/lib/postgresql/dump
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - ".env" 
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    networks:
        - backend
networks:  
  backend:  
    name: php_backend
    driver: bridge